### ISSUE TITLE
installed and did the setup but blank page instead of maintenance

### ISSUE THREAD

**Issue by balasivagnanam** [pointia/Biztech_Easymaintanance#1]
My magento conenct was not working so I had to copyover the files to my installation, clear the cache and logout and login. 

I could do the setting on admin side and its working fine, no one except the configured IP are able to see the site.

however I see a blank page instead of maintenance page. Please help.

**Comment by pointia** [comment]
Try to copy the files from inside app/design/frontend/default/ into the app/design/frontend/base and let me know if it works. 

Could you also provide some further information like Magento Version, if you use modman, composer and so on?

**Comment by balasivagnanam** [comment]
works after copying the files to frontend/base

I copy the files and clear cache, I dont use modman or composer.

My magento is 1.9.1

But currently even if I dont have any image applied for logo, there is an image water mark.

The logo which you see below is from wizwiz editor as I get better control of what goes in there and layout. So I want to remove the eazylogo image missing content.

![image](https://cloud.githubusercontent.com/assets/4233785/14269397/cc31527a-fb16-11e5-825b-00a7f8955615.png)

**Comment by pointia** [comment]
The Problem was that you didn't use modman to install the extension. I'm not the maintainer of the module I'm using it just for myself. 

Nontheless I updated the version of the module that it works without modman oder composer and added an addtional if tag thus the described Logo wan't appear if no logo is uploaded or selected.

So just update the extension and you should be fine.
